---
repositories:
  linuxcnc-ethercat:
    type: git
    url: https://github.com/zultron/linuxcnc-ethercat.git
    version: zultron/2025-07-31-fix_linker_error
  machinekit-hal:
    type: git
    url: https://github.com/thebyohazard/machinekit-hal.git
    version: noble
  hal_ros_control:
    type: git
    # url: https://github.com/tormach/hal_ros_control.git
    url: https://github.com/thebyohazard/hal_ros_control.git
    version: jazzy-devel
  hw_device_mgr:
    type: git
    url: https://github.com/tormach/hw_device_mgr.git
    version: humble-devel
  # ros2_control_demos:
  #   # FIXME:  hal_ros_control hal_rrbot_control uses
  #   # ros2_control_demos with patches to parameterize the ros2_control
  #   # hardware interface plugin.
  #   type: git
  #   url: https://github.com/zultron/ros2_control_demos.git
  #   version: zultron/2023-04-14-humble-dev-parameterize-hardware-plugin
